### PR TITLE
added travis.yml deployment config

### PR DESCRIPTION
**Pull request by fizyk**
- ignore PyCharm IDE files

### CODE REVIEW

**Comment by trojkat** [comment]
:+1:

**Comment by tomislater** [comment]
I think we have to pass `extras_require` param in `setup` function (`setup.py`)

**Comment by fizyk** [comment]
I know that we have to, @trojkat is dealing with tests in #2 as it seems. I'd be okay with separate pull requests for each issues discovered though.

**Comment by tomislater** [comment]
:+1:

**Comment by tomislater** [comment]
Please, help me. Merge it

**Pull request merged**
